Introduces local sized caches
scireum/sirius-kernel pull request #295
Opened 2020-11-04 16:09 UTC by idlira

This rather simple class enables one to create a local cache limited by the amount of entries in it. By local I really mean local, without any framework-based lifetime. Create and destroy it at will. See it as a sort of `Map<String, Object>` with a maximum size.

It can be initialized with a default loader used by the `get(key)` method, or a loader can be provided ad-hoc in the `get(key, loader)`.

2020-12-11 11:00 UTC, qw3ry approved these changes

2020-12-11 11:01 UTC, sabieber requested changes

2020-12-11 11:20 UTC, idlira commented on src/main/java/sirius/kernel/cache/SizedCache.java
> +        if (maximumSize == 0) {
Good point. Resolving in a more generic place.

2020-12-11 11:55 UTC, sabieber approved these changes

2020-12-17 08:28 UTC, andyHa commented on src/main/java/sirius/kernel/cache/SizedCache.java
> +    public SizedCache(String configKey, Function<String, T> defaultValueComputer) {
I'd remove this as provide a config value leaves the false impression that we could control the cache size - we cannot, as there can be many instances of the same cache.

2020-12-17 09:04 UTC, sabieber approved these changes

2020-12-17 10:50 UTC, jmuscireum approved these changes

2020-12-17 10:51 UTC, merged