Sort caches in the cache-command
scireum/sirius-kernel pull request #300
Opened 2020-11-23 09:22 UTC by ymo-sci

2020-11-23 09:33 UTC, mkeckmkeck requested changes

2020-11-23 09:33 UTC, mkeckmkeck commented on src/main/java/sirius/kernel/cache/ManagedCache.java
> +import java.util.*;
Don't use wildcard import, check your ide settings

2020-11-24 09:07 UTC, mkeckmkeck approved these changes

2020-11-24 09:20 UTC, idlira approved these changes

2020-11-24 09:21 UTC, qw3ry commented on src/main/java/sirius/kernel/cache/CacheManager.java
>      }
```suggestion
        return caches.values().stream().sorted(Comparator.comparing(Cache::getName)).collect(Collectors.toList());
    }
```
würde auch gehen, dann spart man sich den comparator unten

2020-11-24 09:21 UTC, qw3ry approved these changes

2020-11-24 10:07 UTC, sabieber approved these changes

2020-11-24 10:36 UTC, qw3ry approved these changes

2020-11-24 10:37 UTC, merged