Provides a helper for Spliterators and a getter for Limit.
scireum/sirius-kernel pull request #306
Opened 2021-01-26 16:31 UTC by andyHa

2021-01-26 16:54 UTC, idlira requested changes
small javadoc typos

2021-01-26 16:54 UTC, idlira commented on src/main/java/sirius/kernel/commons/PullBasedSpliterator.java
> + * This can be used if data ob unknown size is loaded "page by page" and is to be processed as a
```suggestion
 * This can be used if data of unknown size is loaded "page by page" and is to be processed as a
```

2021-01-26 16:54 UTC, idlira commented on src/main/java/sirius/kernel/commons/PullBasedSpliterator.java
> +     * and "empty iterator" (where {@link Iterator#hasNext()} is <tt>false</tt>) to signal that the end of
```suggestion
     * an "empty iterator" (where {@link Iterator#hasNext()} is <tt>false</tt>) to signal that the end of
```

2021-01-26 16:57 UTC, bwiedmann approved these changes

2021-01-27 07:38 UTC, sabieber requested changes

2021-01-27 07:38 UTC, sabieber commented on src/main/java/sirius/kernel/commons/PullBasedSpliterator.java
> + * Provides a base implementation for {@link Spliterator spliterators} which internally pull lists of data.
```suggestion
 * Provides a base implementation for {@link Spliterator spliterators} which internally pulls lists of data.
```

2021-01-27 08:36 UTC, qw3ry approved these changes

2021-01-27 08:36 UTC, qw3ry commented on src/main/java/sirius/kernel/commons/Limit.java
> +        this.itemsToSkip = Math.max(itemsToSkip, 0);
Wär das nicht eher n Fall für ne IllegalArgumentException? Wär dann allerdings potentiell breaking, und passt auch so

2021-01-27 09:52 UTC, sabieber approved these changes

2021-01-27 09:55 UTC, idlira approved these changes

2021-01-27 09:55 UTC, mkeckmkeck approved these changes

2021-01-27 09:55 UTC, merged