Generalize the AutoTransformLoadAction, so client code can extend on it easily
scireum/sirius-kernel pull request #312
Opened 2021-02-12 09:52 UTC by qw3ry

2021-02-12 10:05 UTC, sabieber requested changes

2021-02-12 10:05 UTC, sabieber commented on src/main/java/sirius/kernel/di/transformers/AutoTransformLoadAction.java
> +        private final int priority;
Wär super wenn beim nächsten PR Codestyle und echte Änderung in zwei Commits aufgeteilt wäre 😇

2021-02-12 10:05 UTC, sabieber commented on src/main/java/sirius/kernel/di/transformers/AutoTransformLoadAction.java
> +            ctx.registerPart(new AutoTransformer<>(clazz,
ctx -> mutableContext?

2021-02-12 10:49 UTC, sabieber approved these changes

2021-02-15 07:09 UTC, mkeckmkeck requested changes

2021-02-15 07:09 UTC, mkeckmkeck commented on src/main/java/sirius/kernel/di/transformers/AutoTransformLoadAction.java
> +        }
Why do we need this check? Wouln't this bring the possibility to create a transformer to Object?

2021-02-15 18:19 UTC, andyHa approved these changes

2021-02-16 09:15 UTC, mkeckmkeck approved these changes

2021-02-16 09:26 UTC, jmuscireum approved these changes

2021-02-16 09:26 UTC, merged