Displays the node metrics sorted by metric name
scireum/sirius-kernel pull request #313
Opened 2021-02-15 16:19 UTC by sabieber

2021-02-15 16:21 UTC, andyHa commented on src/main/java/sirius/kernel/health/metrics/Metric.java
> +        if (Strings.areEqual(label, o.label)) {
```suggestion
        if (!Strings.areEqual(label, o.label)) {
```

2021-02-15 16:22 UTC, meg1502 approved these changes

2021-02-15 16:23 UTC, andyHa approved these changes

2021-02-15 16:23 UTC, andyHa commented on src/main/java/sirius/kernel/health/metrics/Metric.java
> +        if (Strings.areEqual(label, o.label)) {
or chain Comparators...

2021-02-15 16:56 UTC, idlira requested changes
...

2021-02-15 16:56 UTC, idlira commented on src/main/java/sirius/kernel/health/metrics/Metric.java
>       * @return the ocde of this metric.
```suggestion
     * @return the code of this metric.
```

2021-02-15 16:56 UTC, idlira commented on src/main/java/sirius/kernel/health/metrics/Metric.java
> +        if (!Strings.areEqual(label, o.label)) {
rename o -> other ?

2021-02-16 06:58 UTC, mkeckmkeck approved these changes

2021-02-16 07:33 UTC, idlira approved these changes

2021-02-16 07:33 UTC, merged