Adds support for protocol changing HTTP redirects.
scireum/sirius-kernel pull request #350
Opened 2021-08-23 15:41 UTC by andyHa

HttpUrlConnection does not follow redirects if the protocol is changed.
We fix this, as redirects (from HTTP to HTTPS) are quite common.

The implementation is heavily inspired by
https://mkyong.com/java/java-httpurlconnection-follow-redirect-example/

Fixes: SIRI-412

2021-08-23 16:05 UTC, meg1502 requested changes
We probably also need to call connect in the getHeaderField methods?

2021-08-23 16:34 UTC, meg1502 approved these changes

2021-08-24 08:19 UTC, sabieber approved these changes

2021-08-24 08:23 UTC, qw3ry approved these changes

2021-08-24 08:31 UTC, idlira approved these changes

2021-08-24 09:11 UTC, merged