Adds StructuredOutput.amountProperty
scireum/sirius-kernel pull request #394
Opened 2022-05-24 10:22 UTC by idlira

**BREAKING** which writes Amounts to StructuredOutput, formatting the output with the provided NumberFormat and giving the possibility to strip trailing zeros (smart round).

Marked as breaking since classes extending AbstractStructuredOutput must implement a new method.

Fixes: OX-8608

2022-05-24 10:24 UTC, sabieber approved these changes

2022-05-24 11:00 UTC, andyHa requested changes

2022-05-24 11:00 UTC, andyHa commented on src/main/java/sirius/kernel/xml/AbstractStructuredOutput.java
> +        }
I think we need a proper way to forward this as for JSON this will otherwise add ' around it...

2022-05-24 15:09 UTC, sabieber approved these changes

2022-05-24 15:10 UTC, andyHa commented on src/main/java/sirius/kernel/xml/AbstractStructuredOutput.java
> +        if (amount == null || Amount.NOTHING.equals(amount)) {
```suggestion
        if (amount == null || amount.isEmpty()) {
```

2022-05-24 15:12 UTC, cschierle approved these changes

2022-05-25 07:52 UTC, mkeckmkeck approved these changes

2022-05-25 11:22 UTC, merged