SIRI-624 also fine-log http-errors on soap-client
scireum/sirius-kernel pull request #414
Opened 2022-10-28 09:10 UTC by ymo-sci

e.g. on a 500 - HTTP-Response now the fine-log also logs the request and won´t die with the exception before.

- fixes: SIRI-624

2022-10-28 09:41 UTC, andyHa requested changes

2022-10-28 09:41 UTC, andyHa commented on src/main/java/sirius/kernel/xml/SOAPClient.java
> +                            "---------- call ----------\n%s\n---------- response ----------\n%s---------- end ----------",
```suggestion
                            """
                               ---------- call ----------
                               %s
                               ---------- response ----------
                               %s
                               ---------- end ----------
                               """,
```

2022-10-28 09:41 UTC, andyHa commented on src/main/java/sirius/kernel/xml/SOAPClient.java
> +            StructuredNode result = null;
nope - extract method...

2022-10-31 07:36 UTC, oolscireum approved these changes

2022-11-02 09:35 UTC, idlira approved these changes

2022-11-03 08:49 UTC, andyHa commented on src/main/java/sirius/kernel/xml/SOAPClient.java
> +            StructuredNode result = null;
it more or less an obvious indicator that the given logic is to be separated into its own method....

2022-11-07 10:50 UTC, sabieber approved these changes

2022-11-07 11:00 UTC, idlira approved these changes

2022-11-07 11:20 UTC, oolscireum approved these changes

2022-11-07 12:18 UTC, mko-sci approved these changes

2022-11-07 12:59 UTC, andyHa approved these changes

2022-11-07 13:04 UTC, cschierle approved these changes

2022-11-07 14:15 UTC, merged