NLS: Adds a method which converts a given time range in milliseconds to a time representation format typically found in digital clocks
scireum/sirius-kernel pull request #443
Opened 2023-02-23 10:06 UTC by mko-sci

Fixes: [OX-9555](https://scireum.myjetbrains.com/youtrack/issue/OX-9555/Video-Modernisierung-Offene-Punkte)

2023-02-23 10:08 UTC, sabieber approved these changes

2023-02-23 10:08 UTC, sabieber commented on src/main/java/sirius/kernel/nls/NLS.java
> +     * Converts the given time range in milliseconds to a time representation format typically found in digital clocks.
```suggestion
     * Converts the given time range in milliseconds to a time representation format typically found in digital clocks (like 12:05:17).
```

Wär schon nett wenn das JavaDoc sagt wie es hinterher aussieht :)

2023-02-23 13:50 UTC, sabieber requested changes

2023-02-23 13:50 UTC, sabieber commented on src/main/java/sirius/kernel/nls/NLS.java
>          }
Syntactically this is not entirely the same logic as before.
Before: includeMillis only was applied when includeSeconds AND includeMillis is set to true
After: includeMillis can be set to true while includeSeconds is disabled

2023-02-23 13:50 UTC, sabieber commented on src/main/java/sirius/kernel/nls/NLS.java
> +        return convertDuration(Duration.ofMinutes(duration), includeSeconds, includeMillis);
```suggestion
        return convertDuration(Duration.ofMillis(duration), includeSeconds, includeMillis);
```

2023-02-23 15:50 UTC, idlira requested changes

2023-02-23 15:50 UTC, idlira commented on src/main/java/sirius/kernel/nls/NLS.java
> +        if (minutes > 0) {
Exact minutes will not be added? like exact 3 hours to be 03:00... ?

2023-02-23 15:50 UTC, idlira commented on src/main/java/sirius/kernel/nls/NLS.java
> +        if (minutes > 0) {
A unit test would be nice to verify diverse variants.

2023-02-24 10:30 UTC, sabieber approved these changes

2023-02-24 10:30 UTC, sabieber commented on src/test/java/sirius/kernel/nls/NLSSpec.groovy
> +        Duration.ofDays(2l).plusMinutes(1L)                 | "48:01:00"
```suggestion
        Duration.ofDays(2L)                                 | "48:00:00"
        Duration.ofDays(2L).plusHours(1L)                   | "49:00:00"
        Duration.ofDays(2L).plusMinutes(1L)                 | "48:01:00"
```

2023-02-24 10:32 UTC, idlira approved these changes

2023-02-24 10:44 UTC, fhaScireum approved these changes

2023-02-24 10:44 UTC, fhaScireum commented on src/test/java/sirius/kernel/nls/NLSSpec.groovy
> +                .ofMinutes(60L)   | true          | true         | "1 Stunde"
Ist das richtig formattiert?

2023-02-24 10:53 UTC, mko-sci commented on src/test/java/sirius/kernel/nls/NLSSpec.groovy
> +                .ofMinutes(60L)   | true          | true         | "1 Stunde"
nö, aber jetzt. 
Da kackt IntelliJ regelmäßig ab...

2023-02-24 10:54 UTC, fhaScireum approved these changes

2023-02-24 11:01 UTC, sabieber commented on src/test/java/sirius/kernel/nls/NLSSpec.groovy
> +                .ofMinutes(60L)   | true          | true         | "1 Stunde"
Ein Grund wieso Groovy weg soll :)

2023-02-27 08:56 UTC, andyHa approved these changes

2023-02-27 09:20 UTC, merged