SIRI-823: Replaces the "..." with the single symbol "…"
scireum/sirius-kernel pull request #465
Opened 2023-06-23 08:56 UTC by oolscireum

because the shorten(…) method removes only one symbol from the overall textlength.

Fixes: SIRI-823

2023-06-23 09:07 UTC, idlira requested changes
I think we should keep the ascii chars and cut it properly since we are adding 3 chars.

2023-06-23 10:13 UTC, andyHa requested changes
Also, we cannot rely on this method to correctly produce a limited string anyways (see JavaDoc) - maybe simply use Strings.limit?

2023-06-23 10:14 UTC, andyHa commented
Also, we should fix the javadoc of the method (no uppercase letter at the start of the sentence. odd linebreaks no reference to "limit" via @see

2023-06-26 06:33 UTC, idlira approved these changes

2023-06-26 07:21 UTC, ymo-sci approved these changes

2023-06-26 07:22 UTC, fhaScireum approved these changes

2023-06-26 09:13 UTC, mkeckmkeck approved these changes

2023-06-26 14:36 UTC, andyHa approved these changes

2023-06-27 12:04 UTC, merged