add an often needed isUrl check to Strings
scireum/sirius-kernel pull request #540
Opened 2024-11-22 10:49 UTC by ymo-sci

### Description

### Additional Notes

- This PR fixes or works on following ticket(s): No ticket, 
- This PR is related to PR: 

### Checklist

- [x] Code change has been tested and works locally
- [x] Code was formatted via IntelliJ and follows SonarLint & [best practices](https://scireum.myjetbrains.com/youtrack/articles/MISC-A-16/CodeStyle-JavaDoc)
- [ ] Patch Tasks: Is local execution of Patch Tasks necessary? If so, please also mark the PR with the tag.

2024-11-22 10:57 UTC, idlira requested changes

2024-11-22 10:57 UTC, idlira commented on src/main/java/sirius/kernel/commons/Strings.java
> +    private static final Pattern URL_PATTERN = Pattern.compile("^https?://", Pattern.CASE_INSENSITIVE);
```suggestion
    private static final Pattern HTTP_URL_PATTERN = Pattern.compile("^https?://", Pattern.CASE_INSENSITIVE);
```

2024-11-22 10:57 UTC, idlira commented on src/main/java/sirius/kernel/commons/Strings.java
> +    public static boolean isUrl(@Nullable String value) {
Required: rename to isHttpUrl, since `file://...`, `ftp://` are also URLs (the protocol is not part of it)

2024-11-22 11:02 UTC, idlira approved these changes

2024-11-22 11:05 UTC, mkeckmkeck approved these changes

2024-11-22 11:12 UTC, jakobvogel approved these changes

2024-11-22 11:12 UTC, jakobvogel commented on src/test/kotlin/sirius/kernel/commons/StringsTest.kt
> +        assertTrue(Strings.isHttpUrl("https://example.com"))
Please provide more test cases
- with username & password
- with username, w/o password
- with path
- with port

2024-11-22 12:31 UTC, jakobvogel commented on src/test/kotlin/sirius/kernel/commons/StringsTest.kt
> +        assertTrue(Strings.isHttpUrl("http://example.com?user=foo&password="))
We can leave them, but I meant something like `http://user@server.com/path` or `http://user:password@server.com/path`

2024-11-22 12:56 UTC, sabieber approved these changes

2024-11-22 13:11 UTC, jakobvogel approved these changes

2024-11-22 13:14 UTC, jakobvogel commented on src/test/kotlin/sirius/kernel/commons/StringsTest.kt
> +        assertTrue(Strings.isHttpUrl("https://example.com"))
The more I think about it, the more I would prefer a `@ParameterizedTest` with `@CsvSource` (or the like) … as the individual asserts are mutually independent and should thus be considered separately, not consecutively.

2024-12-02 16:02 UTC, jakobvogel approved these changes
🙏

2024-12-03 14:07 UTC, merged