Feature/ymo/siri 1037 xxe
scireum/sirius-kernel pull request #543
Opened 2024-12-09 14:33 UTC by ymo-sci

### Description
Fix a potential XXE vulnerability via setting Feature Secure Processing
https://docs.oracle.com/javase/8/docs/technotes/guides/security/jaxp/jaxp.html#feature-for-secure-processing

### Additional Notes

- This PR fixes or works on following ticket(s): [SIRI-1037](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1037)
- Fixes Issue https://github.com/scireum/sirius-kernel/issues/536
- This PR is related to PR: 

### Checklist

- [x] Code change has been tested and works locally
- [x] Code was formatted via IntelliJ and follows SonarLint & [best practices](https://scireum.myjetbrains.com/youtrack/articles/MISC-A-16/CodeStyle-JavaDoc)
- [ ] Patch Tasks: Is local execution of Patch Tasks necessary? If so, please also mark the PR with the tag.

2024-12-09 15:08 UTC, sabieber requested changes
Would welcome more (or rather any) info in the commit messages.
Commit messages should be the first source of information when debugging an issue or trying to understand a change.

2024-12-09 15:20 UTC, mko-sci commented on src/main/java/sirius/kernel/xml/XMLReader.java
> +            factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
Optional: Konstante rausziehen

2024-12-09 15:20 UTC, mko-sci approved these changes

2024-12-09 15:31 UTC, scireum-mbo approved these changes

2024-12-09 17:19 UTC, jakobvogel approved these changes

2024-12-10 06:37 UTC, mkeckmkeck approved these changes

2024-12-10 07:17 UTC, sabieber approved these changes

2024-12-10 07:17 UTC, idlira approved these changes

2024-12-10 08:25 UTC, fhaScireum approved these changes

2024-12-10 08:57 UTC, jmuscireum approved these changes

2024-12-10 10:36 UTC, sabieber approved these changes

2024-12-11 08:01 UTC, merged